name: Continuous Integration
on:
  push:
jobs:
  norm:
    name: norminette
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip setuptools
          python3 -m pip install norminette
      - name: Run Norminette
        run: make norm
  build:
    name: Build + Check allowed functions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build push_swap
        run: make
      - name: Clean push_swap
        run: make fclean
      - name: Build checker
        run: make bonus
      - name: Build push_swap
        run: make
      - name: check
        run: nm push_swap && nm checker
      - name: check allowed_functions
        run: test/check_allowed_functions.sh
  unit_test:
    name: unit_test
    runs-on: macos-12
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build push_swap
        run: make
      - name: Unit test
        run: make test
  e2e_test:
    runs-on: macos-12
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build push_swap
        run: make
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
      - name: Run tests
        run: rake test
